version: "3"

services:
  rocket:
    build: ./api_server
    ports: 
      - "3001:3001"
    volumes:
      - ./api_server:/usr/src/app
    env_file:
      - ./.envs/.local/.rocket
    links:
      - db
    # diesel infer_schema macro gives warnings with this flag.
    # environment:
    #   - CARGO_INCREMENTAL=1
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo update && cargo watch -x run"

  db:
    image: "postgres:11.3"
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
